### ISSUE TITLE
Upgrade to Kie 6.1.0.Final

### ISSUE THREAD

**Issue by dm-conti** [maciejwalkowiak/junit-drools#6]
Upgrade project to a new API (Kie 6.0.1.Final).
For this reason I added the bom version 6.1.0.Final and I modified loading KnowledgeSession to use a new API.

**Comment by maciejwalkowiak** [comment]
Unfortunately due to the lack of time I am not able to continue developing and maintaining `junit-drools` project. Thank you for your contributions and I hope you will find one of the forks still maintained and helpful for you!
